// <auto-generated />
using FreshMarqueSnails.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FreshMarqueSnails.Migrations
{
    [DbContext(typeof(CustomerOrderContext))]
    partial class CustomerOrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("FreshMarqueSnails.Models.CustomerOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("DeliveryStatus");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.ToTable("CustomerOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
